### ISSUE TITLE
descriptive Readme

### ISSUE THREAD

**Issue by krishnajalan** [jklu-jaipur/jklu-fraternity-network#3]
A brief description of what the project is about will make it easier for the user to understand the repository before downloading and running on a local machine.

**Comment by samyak-bhagat** [comment]
@krishnajalan  we are working on it we will update readme file soon

**Comment by samyak-bhagat** [comment]
> A brief description of what the project is about will make it easier for the user to understand the repository before downloading and running on a local machine.
